name: 🪲 Report a bug
description: Create a bug report to help improve this Firmware
title: "[BUG] "
body:
  - type: markdown
    attributes:
      value: |
        # Bug Details
        #### You can also use this form to suggest any fix no matter how simple, it doesn't have to be a 'bug' per say.

  - type: dropdown
    attributes:
      label: Did you test the latest release build?
      description: >-
        Always try the [latest](https://github.com/classicrocker883/MriscocProUI/releases/latest) - most recently updated firmware
      options:
        - Yes, and the problem still exists.
        - No, but I will try it!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug Description

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Be clear and concise of the
        problem and include as many details as possible.

        Use ` ```y ` before and  ` ``` ` after (on its own line) when pasting formatted code.
      placeholder: |
        A does B, supposed to do C.
        X doesn't work.
        
        Please describe the steps needed to reproduce the issue.
        1. [First Step] ...
        2. [Second Step] ...
        3. [and so on] ...

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Your Setup

  - type: dropdown
    attributes:
      label: Printer Model
      description: Which Printer are you using?
      options:
        - Voxelab Aquila
        - Creality Ender-3
        - Other (explain below)

  - type: input
    attributes:
      label: Model Type
      description: OG, X2, X3, S2, S3, D1, Pro, V2, S1, Neo, Pro, Max, Other

  - type: dropdown
    attributes:
      label: Your Mainboard
      description: Which Chip?
      options:
        - GD32
        - N32
        - HC32
        - Creality V4.2.7
        - Creality V4.2.2
        - BTT SKR MINI E3 V2
        - BTT SKR MINI E3 V3
        - Other (other than listed above)

  - type: input
    attributes:
      label: Other Mainboard Type
      description: If not listed above

  - type: input
    attributes:
      label: Add-ons that could be involved
      description: (BL/3D/CR Touch)

  - type: dropdown
    attributes:
      label: ProUI?
      description: Are you using ProUI or NoPro?
      options:
        - ProUI
        - NoPro
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Bed Leveling
      description: What kind of bed leveling are you using?
      options:
        - UBL - Unified Bed Leveling
        - BLT - BL Touch Bilinear mesh
        - MM - Manual Mesh Bed Leveling
        - Default - No Probe / No Bed Leveling
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Attachments

  - type: checkboxes
    attributes:
      label: Did you include your own configuration files?
      options:
        - label: A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

  - type: markdown
    attributes:
      value: |
        ### Optional items to include:
        - Log output from the host. (`M111 S247` for maximum logging.)
        - Images or videos demonstrating the problem, if it helps to make it clear.
        - A G-Code file that exposes the problem, if not affecting _all_ G-code.

  - type: textarea
    attributes:
      label: Additional information & file uploads
      description: >-
        If you've made any other modifications to the firmware, please describe them in detail.

        Don't forget to put ` ```y ` before and  ` ``` ` after (on its own line) when pasting formatted code.
